config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :friends
  #get 'home/index'
  get 'home/about'
  #root 'home#index'
  root 'friends#index'
  #get 'search', to:"friends#search"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/friend.rb
class Friend < ApplicationRecord
  belongs_to :user
  FRIEND_TYPE = ["School", "Family", "College", "Bar","Work"]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_many :friends


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :set_friend, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]
  # GET /friends or /friends.json
  def index
    @friends = Friend.all
  end

  # GET /friends/1 or /friends/1.json
  def show
  end

  # GET /friends/new
  def new
    #@friend = Friend.new
    @friend = current_user.friends.build
  end

  # GET /friends/1/edit
  def edit
  end

  # POST /friends or /friends.json
  def create
    #@friend = Friend.new(friend_params)
    @friend = current_user.friends.build(friend_params)

    respond_to do |format|
      if @friend.save
        format.html { redirect_to @friend, notice: "Friend was successfully created." }
        format.json { render :show, status: :created, location: @friend }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /friends/1 or /friends/1.json
  def update
    respond_to do |format|
      if @friend.update(friend_params)
        format.html { redirect_to @friend, notice: "Friend was successfully updated." }
        format.json { render :show, status: :ok, location: @friend }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friends/1 or /friends/1.json
  def destroy
    @friend.destroy
    respond_to do |format|
      format.html { redirect_to friends_url, notice: "Friend was successfully destroyed." }
      format.json { head :no_content }
    end
  end


def correct_user
  @friend = current_user.friends.find_by(id: params[:id])
  redirect_to friends_path, notice: "I am sorry, but you are not authorized to edit this friend." if @friend.nil?
end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friend
      @friend = Friend.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def friend_params
      params.require(:friend).permit(:first_name, :last_name, :email, :twitter, :user_id, :friend_type)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  end

  def about
    @about_me = "My name is Lucas Weinmann"
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/friends/_form.html.erb
<%= form_with(model: friend) do |form| %>
  <% if friend.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(friend.errors.count, "error") %> prohibited this friend from being saved:</h2>
      <ul>
        <% friend.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<br/>
  <div class="field form-group">
    <%= form.text_field :first_name, class: "form-control", placeholder: "First name" %>
  </div>
<br/>
  <div class="field form-group" required>
    <%= form.text_field :last_name, class: "form-control", placeholder: "Last name" %>
  </div>
<br/>
  <div class="field form-group">
    <%= form.text_field :email, class: "form-control", placeholder: "Email" %>
  </div>
<br/>
  <div class="field form-group">
    <%= form.text_field :twitter, class: "form-control", placeholder: "Twitter" %>
  </div>
<br/>
<div class="field form-group">
  <%= form.number_field :user_id, id: :friend_user, class: "form-control", value: current_user.id, type: :hidden %>
</div>
<div class="field form-select">
  <%= form.select :friend_type, Friend::FRIEND_TYPE, {class:"form-control"}, prompt: "Which type of friend is this?" %>
</div>
<br/>
  <div class="actions">
    <%= form.submit class: "btn btn-dark"  %>
  </div>
<% end %>

app/views/friends/edit.html.erb
<h1>Editing Friend</h1>
<br/>
<%= render 'form', friend: @friend %>
<br/>
<%= link_to 'Delete', @friend, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-outline-danger" %>
<br/>
<br/>
<%= link_to 'Back', friends_path, class:"btn btn-light" %>

app/views/friends/index.html.erb
<link rel="preconnect" href="https://fonts.gstatic.com">
<link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@100&display=swap" rel="stylesheet">
<style>
.logo {
   font-size: 100px;
   padding: 50px;
   font-family: 'Montserrat', sans-serif;
   text-align: center;
   background: white;
   box-shadow: 0 20px 20px rgba(0,0,0,0.05), 0 6px 6px rgba(0,0,0,0.23);
}
 }
</style>


<% if user_signed_in? %>

<!--
<br/>
<br/>

  <div class="container-fluid">
    <form class="d-flex" action="/search">
      <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success" type="submit">Search</button>
    </form>
  </div>

  <br/>
  <br/>
-->
  <table class="table table-bordered table-hover">
    <thead class="thead-dark">
      <tr>
        <th>Name</th>
        <th>Email</th>
        <th>Twitter</th>
        <!--<th>User ID</th>-->
        <th>Type</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @friends.each do |friend| %>
      <% if friend.user == current_user %>
        <tr>
          <td><%= link_to friend.first_name + " " + friend.last_name, friend %></td>
          <td><%= link_to friend.email, "mailto::" + friend.email, target: "_blank" %></td>
          <td><%= link_to friend.twitter, "https://www.twitter.com/" + friend.twitter, target: "_blank" %></td>
          <!--<td><%= friend.user_id %></td>-->
          <!--<td><%= link_to 'Edit', edit_friend_path(friend), class:"btn btn-outline-secondary btn-sm" %></td>-->
          <td><%= friend.friend_type %></td>
          <td><%= link_to 'Delete', friend, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-outline-danger btn-sm" %></td>
        </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Friend', new_friend_path, class:"btn btn-dark" %>

<% else %>
<div class="logo">
FRIENDS
</div>
<br/>
<br/>
<h1>If you are here, it means you are a dear friend of mine. </h1>
<br/>
<p>This is my first app. I am starting to learn a basic CRUD.</p>
<p>This is a very simple thing where you can manage a list of your friends.</p>
<% end %>

app/views/friends/new.html.erb
<h1>New Friend</h1>
<br/>
<%= render 'form', friend: @friend %>
<br/>
<%= link_to 'Back', friends_path, class:"btn btn-light" %>

app/views/friends/search.erb
<!--
<h1>Results</h1>

<%= render @friend %>
-->

app/views/friends/show.html.erb
<div class="card">
  <div class="card-header">
    Friend's info
  </div>
  <div class="card-body">
    <h2 class="card-title"><%= @friend.first_name %> <%= @friend.last_name %></h2>
    <br/>
    <p class="card-text">Email: <%= @friend.email %></p>
    <p class="card-text">Twitter: <%= @friend.twitter %></p>
    <p class="badge rounded-pill bg-warning"><%= @friend.friend_type %></p>
  
  </div>
</div>
<br/>
<%= link_to 'Edit', edit_friend_path(@friend), class:"btn btn-light" %>
<%= link_to 'Back', friends_path, class:"btn btn-light" %>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">

  <div class="container-fluid">
    <%=
      link_to 'F R I E N D S',
      root_path,
      class:"navbar-brand"
    %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to 'About us',
            home_about_path,
            class: "nav-link" %>
        </li>
      <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to 'Add friend',
            new_friend_path,
            class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Sign out',
            destroy_user_session_path, method: :delete,
            class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'My profile',
            edit_user_registration_path,
            class: "nav-link" %>
        </li>
        <% else %>
          <li class="nav-item">
            <%= link_to 'Sign up',
              new_user_registration_path,
              class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to 'Sign in',
              new_user_session_path,
              class: "nav-link" %>
          </li>
      <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/home/about.html.erb
<h1>About me</h1>

<p><%= @about_me %></p>

<a href="https://www.lucaspic.com/"><strong>Check my portfolio</strong></a>

<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-arrow-up" viewBox="0 0 16 16">
  <path fill-rule="evenodd" d="M8 15a.5.5 0 0 0 .5-.5V2.707l3.146 3.147a.5.5 0 0 0 .708-.708l-4-4a.5.5 0 0 0-.708 0l-4 4a.5.5 0 1 0 .708.708L7.5 2.707V14.5a.5.5 0 0 0 .5.5z"/>
</svg>

app/views/home/index.html.erb
<h1>HELLO world!</h1>
<p>This is my first app.</p>
<p>I am starting to learn a basic CRUD.</p>
<p>This is an app where you can manage a list of your friends.</p>

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">

    <title>Friends app</title>
      <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>
  <body>


    <%= render 'home/header' %>
    <div class='container'>
      <br/>
        <% if notice %>
          <%= render 'layouts/alerts' %>
        <% end %>
        <br/>
        <%= yield %>
    </div>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.min.js" integrity="sha384-Atwg2Pkwv9vp0ygtn1JAojH0nYbwNJLPhwyoVbhoPwBhjQPR5VtM2+xf0Uwh9KtT" crossorigin="anonymous"></script>
    -->
  </body>
</html>